version: '3.9'

services:
  redis:
    image: 'redis:alpine'
    restart: always
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379
  db:
    image: 'postgres:15-alpine'
    restart: always
    environment:
      POSTGRES_USER: botflow
      POSTGRES_PASSWORD: botflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  redis_data:
  postgres_data:
